{
 "title": "shorty",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Responses by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status_code, method, path) (increase(shorty_http_requests_total{}[$__rate_interval])) != 0",
     "legendFormat": "{{status_code}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Responses by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status_code, method, path) (increase(shorty_http_requests_total{status_code=~\"[45][0-9][0-9]\"}[$__rate_interval])) != 0",
     "legendFormat": "{{status_code}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Duration by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(shorty_http_request_duration_seconds_sum[$__range])\n/\n  rate(shorty_http_request_duration_seconds_count[$__range])",
     "legendFormat": "{{status_code}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shorty_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(shorty_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(shorty_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P999"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(shorty_http_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}