include:
  - compose/prometheus.yml
  - compose/grafana.yml
  - compose/postgres.yml
  - compose/seed_data.yml

services:
  resolver:
    image: wiechtig/shorty:latest
    container_name: shorty
    build:
      context: .
      dockerfile: Containerfile
    environment:
      SHORT_LOG_LEVEL: DEBUG
      SHORTY_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/shorty?sslmode=disable"
    ports:
      - "4242:4242"
      - "4343:4343"
    depends_on:
      postgres:
        condition: service_healthy
