//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List short codes
	// (GET /short-codes)
	ListShortCodes(w http.ResponseWriter, r *http.Request, params ListShortCodesParams)
	// Create a new short code
	// (POST /short-codes)
	CreateShortCode(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListShortCodes operation middleware
func (siw *ServerInterfaceWrapper) ListShortCodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShortCodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListShortCodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShortCode operation middleware
func (siw *ServerInterfaceWrapper) CreateShortCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShortCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/short-codes", wrapper.ListShortCodes)
	m.HandleFunc("POST "+options.BaseURL+"/short-codes", wrapper.CreateShortCode)

	return m
}

type ListShortCodesRequestObject struct {
	Params ListShortCodesParams
}

type ListShortCodesResponseObject interface {
	VisitListShortCodesResponse(w http.ResponseWriter) error
}

type ListShortCodes200JSONResponse []ShortCode

func (response ListShortCodes200JSONResponse) VisitListShortCodesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListShortCodes400Response struct {
}

func (response ListShortCodes400Response) VisitListShortCodesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListShortCodes401Response struct {
}

func (response ListShortCodes401Response) VisitListShortCodesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListShortCodes403Response struct {
}

func (response ListShortCodes403Response) VisitListShortCodesResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type ListShortCodes500Response struct {
}

func (response ListShortCodes500Response) VisitListShortCodesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type CreateShortCodeRequestObject struct {
	Body *CreateShortCodeJSONRequestBody
}

type CreateShortCodeResponseObject interface {
	VisitCreateShortCodeResponse(w http.ResponseWriter) error
}

type CreateShortCode201JSONResponse struct {
	Id *string `json:"id,omitempty"`
}

func (response CreateShortCode201JSONResponse) VisitCreateShortCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateShortCode400Response struct {
}

func (response CreateShortCode400Response) VisitCreateShortCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateShortCode401Response struct {
}

func (response CreateShortCode401Response) VisitCreateShortCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateShortCode403Response struct {
}

func (response CreateShortCode403Response) VisitCreateShortCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type CreateShortCode500Response struct {
}

func (response CreateShortCode500Response) VisitCreateShortCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List short codes
	// (GET /short-codes)
	ListShortCodes(ctx context.Context, request ListShortCodesRequestObject) (ListShortCodesResponseObject, error)
	// Create a new short code
	// (POST /short-codes)
	CreateShortCode(ctx context.Context, request CreateShortCodeRequestObject) (CreateShortCodeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListShortCodes operation middleware
func (sh *strictHandler) ListShortCodes(w http.ResponseWriter, r *http.Request, params ListShortCodesParams) {
	var request ListShortCodesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListShortCodes(ctx, request.(ListShortCodesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListShortCodes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListShortCodesResponseObject); ok {
		if err := validResponse.VisitListShortCodesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShortCode operation middleware
func (sh *strictHandler) CreateShortCode(w http.ResponseWriter, r *http.Request) {
	var request CreateShortCodeRequestObject

	var body CreateShortCodeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShortCode(ctx, request.(CreateShortCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShortCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShortCodeResponseObject); ok {
		if err := validResponse.VisitCreateShortCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RVTW/jNhD9K8S0R60tb9qLbk7aBbzoF+oEOQQ+0NLIZkKRzHCYxg303wuSji1/tIjR",
	"055sio/kmzePj29Q285Zg4Y9VG/g6zV2Mv2dry3xjW0wDhxZh8QK05RkJrUMnEe8cQgV2OUj1gx9ATWh",
	"ZGymPJj1TMqs4iy+OkXo86wJWsulRqiYAhanaNUMNlGGcYUUv1tSK2WkviN99hQ/ZH802/fFvrqZcYEv",
	"LvGyIv4X2QIIn4MibKB6GEAPt11EoMc6kOLNPHYxM79GSUjTwOs4WqbRF0udZKjg6/0tFNCgr0k5VtZA",
	"Bb/PfroRX+9vRV4p2D6hETLwGg2rWiZYkY0SeeYtYVf1mtlliZVpbTz0cP9A+lMqAg2S6KSRK+zQsJj+",
	"MYu7KNap/AjZQAEvSD6vLEflaJLkdGikU1DB1agclVCAk7xO5Y7Tuk+1bXL5K0wdip1NzGcNVPCL8rzr",
	"v0/LSXbISB6qh2PCv8pX1YVOmNAtkYRtBaEPmr1gKwg5UNRDRehzQIqcjUzSaNUpftdKZilaGTRDNSnL",
	"Atr3PijDV5/3Eu5s3hfHZH7bkVCMXaLgn5QTS2wtofAsiZVZxe+11RprFrzGLWPhkf+Fqm3bPHmG64eY",
	"LqJNvbPGZ+E/l2X8qa1hNKkH0jm99c/40cdq3ganpXLin+8JW6jgu/E+mMbbVBrvI6nfUZBEcpMNdyjV",
	"VGjlOUqVPCGSJ0Zx5Q+Z2yH8WjbiT3wO6DljJqeYOxPvgSX1NzYZdHUK+mJpqZoGTUT8eO6omWEkI7WY",
	"I70giZ+JbOo2+NB1kjZbjw6Jx82c9WfcfJPSdj7IBcplXNtmc1EPPiR9zsszes93ZJP7EisYhlcMx/7E",
	"JpOLKB6G9MHjMAjMo7j+T67bx0r4UNfofRu03nwzLsm9F1IY/GvglnhB5crv3ottHi764SORom74PDws",
	"4i326bQchCG+VzCOWdsv+n8CAAD//4gUuzUsCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
