// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ShortCode defines model for ShortCode.
type ShortCode struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	CreatedAt   *time.Time              `json:"createdAt,omitempty"`
	ExpiresAt   *time.Time              `json:"expiresAt"`
	Id          *int32                  `json:"id,omitempty"`
	OriginalUrl *string                 `json:"originalUrl,omitempty"`
	ShortCode   *string                 `json:"shortCode,omitempty"`
}

// ShortCodeInput defines model for ShortCodeInput.
type ShortCodeInput struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	ExpiresAt   *time.Time              `json:"expiresAt"`
	OriginalUrl string                  `json:"originalUrl"`
	ShortCode   string                  `json:"shortCode"`
}

// ListShortCodesParams defines parameters for ListShortCodes.
type ListShortCodesParams struct {
	// Limit Maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// PreviousId Last seen ID for pagination
	PreviousId *int32 `form:"previous_id,omitempty" json:"previous_id,omitempty"`
}

// CreateShortCodeJSONRequestBody defines body for CreateShortCode for application/json ContentType.
type CreateShortCodeJSONRequestBody = ShortCodeInput
