enabled: true
realm: "shorty"
displayName: "shorty"

clients:
  - clientId: "shorty"
    enabled: true
    protocol: "openid-connect"
    publicClient: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true # don't do this in production; just for simpler testing
    redirectUris:
      - "http://localhost:4444/*"
    webOrigins:
      - "+"
    attributes:
      pkce.code.challenge.method: "S256"
    protocolMappers:
      - name: "audience-mapper"
        protocol: "openid-connect"
        protocolMapper: "oidc-audience-mapper"
        consentRequired: false
        config:
          included.client.audience: "shorty"
          id.token.claim: "false"
          access.token.claim: "true"

users:
  - username: "user@test.com"
    enabled: true
    emailVerified: true
    firstName: "User"
    lastName: "User"
    email: "user@test.com"
    credentials:
      - type: "password"
        value: "Test123!"
        temporary: false
