services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shorty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorty"]
      interval: 10s
      timeout: 5s
      retries: 6
#    volumes:
#      - type: volume
#        source: db
#        target: /var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../db/migrations:/migrations:ro
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: shorty
    command: >
      -path=/migrations/
      -database postgres://postgres:postgres@postgres:5432/shorty?sslmode=disable
      up
    restart: "no"

volumes:
  db:
