// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortenedLink struct {
	ID          int32
	ShortCode   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	Attributes  []byte
}
