// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shortened_links.sql

package store

import (
	"context"
)

const resolveShortenedLink = `-- name: ResolveShortenedLink :one
SELECT id, original_url FROM shortened_links
WHERE
    LOWER(short_code) = LOWER($1)
    AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type ResolveShortenedLinkRow struct {
	ID          int32
	OriginalUrl string
}

func (q *Queries) ResolveShortenedLink(ctx context.Context, lower string) (ResolveShortenedLinkRow, error) {
	row := q.db.QueryRow(ctx, resolveShortenedLink, lower)
	var i ResolveShortenedLinkRow
	err := row.Scan(&i.ID, &i.OriginalUrl)
	return i, err
}
